server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  data:
    mongodb:
      database: catalog
      port: 27017
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  healthcheck:
    enabled: true
  instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, health, info, ratelimiters, metrics
    health:
      show-details: always
  health:
    circuitbreakers:
      enable: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '50'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '5'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
    instances:
      series:
        baseConfig: default
      movies:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: '3'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError
    instances:
      series:
        baseConfig: default
      movies:
        baseConfig: default
